In [1]:
import pandas as pd
import matplotlib.pyplot as plt

from prophet import Prophet

c:\Users\chiragk\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Importing plotly failed. Interactive plots will not work.

In [2]:
df = pd.read_csv("../data/raw/air_passengers.csv")
df.head()

     Month  Passengers
0  1949-01         112
1  1949-02         118
2  1949-03         132
3  1949-04         129
4  1949-05         121

In [4]:
df = df.rename(columns={
    "Month": "ds",
    "Passengers": "y"
})

df["ds"] = pd.to_datetime(df["ds"])

df.head()

          ds    y
0 1949-01-01  112
1 1949-02-01  118
2 1949-03-01  132
3 1949-04-01  129
4 1949-05-01  121

In [ ]:
plt.figure()
plt.plot(df["ds"], df["y"])
plt.title("Air Passengers Over Time")
plt.xlabel("Date")
plt.ylabel("Passengers")
plt.show()

In [ ]:
model = Prophet()

In [ ]:
model.fit(df)

In [ ]:
future = model.make_future_dataframe(periods=12, freq="ME")
future.tail()

In [ ]:
forecast = model.predict(future)
forecast.head()

In [ ]:
forecast[["ds", "yhat", "yhat_lower", "yhat_upper"]].tail()

In [ ]:
fig = model.plot(forecast)
plt.show()

In [ ]:
fig = model.plot_components(forecast)
plt.show()

In [ ]:
model = Prophet()
model.add_seasonality(name="monthly", period=30.5, fourier_order=5)

model.fit(df)

future = model.make_future_dataframe(periods=12, freq="ME")
forecast = model.predict(future)

model.plot_components(forecast)

In [ ]:
split_index = int(len(df) * 0.8)

train_df = df.iloc[:split_index]
test_df = df.iloc[split_index:]

In [ ]:
model = Prophet()
model.fit(train_df)

future = model.make_future_dataframe(periods=len(test_df), freq="ME")
forecast = model.predict(future)

In [ ]:
pred = forecast["yhat"].tail(len(test_df)).values
actual = test_df["y"].values

plt.figure()
plt.plot(test_df["ds"], actual, label="Actual")
plt.plot(test_df["ds"], pred, label="Predicted")
plt.legend()
plt.show()

In [ ]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(actual, pred)
print("MAE:", mae)